Rails.application.config.assets.precompile += %w( spree/shared/pickup_checkout.js)
Rails.application.config.assets.precompile += %w( spree/shared/map_initializer.js)
Rails.application.config.assets.precompile += %w( spree/shared/spree_states_fetcher.js)
Rails.application.config.assets.precompile += %w( spree/backend/pickup_list_builder.js)
Rails.application.config.assets.precompile += %w( spree/backend/pickup_locations_getter.js)
Rails.application.config.assets.precompile += %w( spree/backend/pickup_translations.js)
Rails.application.config.assets.precompile += %w( spree/frontend/pickup_locations_getter.js)
